app/controllers/VatRegistrationController.scala
app/repositories/RegistrationMongoRepository.scala
app/services/VatRegistrationService.scala
app/services/package.scala
conf/app.routes
it/repository/RegistrationMongoRepositoryISpec.scala
test/controller/VatRegistrationControllerSpec.scala
test/mocks/VatMocks.scala
test/services/VatRegistrationServiceSpec.scala

put my work on top of Reddy's and Darrell's and refactored some repeating patterns

Scrs 4854 trading details

---

app/auth/Authenticated.scala
app/common/exceptions/DBExceptions.scala
app/common/exceptions/LeftState.scala
app/connectors/BusinessRegistrationConnector.scala
app/connectors/test/BusinessRegistrationTestConnector.scala
app/controllers/VatRegistrationController.scala
app/controllers/test/TestSupportController.scala
app/services/VatRegistrationService.scala
conf/application.conf
conf/test.routes
conf/testOnlyDoNotUseInAppConf.routes
test/common/exceptions/LeftStateSpec.scala
test/connectors/BusinessRegistrationConnectorSpec.scala
test/controller/VatRegistrationControllerSpec.scala
test/mocks/VatMocks.scala
test/services/VatRegistrationServiceSpec.scala

fixing error reporting for database exceptions

Test endpoint to create entries in BR backend

---

app/controllers/VatRegistrationBaseController.scala
app/controllers/VatRegistrationController.scala
app/models/VatScheme.scala
app/models/VatSicAndCompliance.scala
app/repositories/RegistrationMongoRepository.scala
app/services/VatRegistrationService.scala
conf/app.routes
it/repository/RegistrationMongoRepositoryISpec.scala
test/controller/VatRegistrationControllerSpec.scala
test/mocks/VatMocks.scala
test/services/VatRegistrationServiceSpec.scala

adding VatSicAndCompliance logical group to VatScheme parent object / persisting business activity description + patch endpoint

[SCRS-3312] Business activity description

---

app/controllers/VatRegistrationBaseController.scala
app/controllers/VatRegistrationController.scala
app/services/VatRegistrationService.scala

also importing only as little of the cats as necessary to compile not importing all of cats implicits package

noticed some forgotten `println`s, so cleaning up

---

app/models/api/VatScheme.scala
app/models/api/VatServiceEligibility.scala
test/models/JsonFormatValidation.scala
test/models/VatAccountingPeriodSpec.scala
test/models/VatBankAccountSpec.scala
test/models/VatChoiceSpec.scala
test/models/VatDigitalContactSpec.scala
test/models/VatServiceEligibilitySpec.scala

and cleaning up tests. found copy-pastes in JsonFormatValidation class

adding VatServiceEligibility 

---

app/models/api/Validation.scala
app/models/api/VatFlatRateScheme.scala
test/models/VatFlatRateSchemeSpec.scala

Reverts hmrc/vat-registration#63

Revert "Scrs 7523 frs start date page"

---

app/models/api/VatServiceEligibility.scala
test/models/VatServiceEligibilitySpec.scala

Added Service Criteria Q5 to the VatServiceEligibility model

---

app/controllers/VatRegistrationController.scala
app/controllers/test/FeatureSwitchController.scala
app/repositories/RegistrationMongoRepository.scala
app/services/SubmissionService.scala
app/utils/FeatureSwitch.scala
conf/application.conf
conf/test.routes
it/api/VatRegistrationBasicISpec.scala
test/mocks/VatMocks.scala
test/services/SubmissionServiceSpec.scala
test/utils/FeatureSwitchSpec.scala

Added feature flag to mock a submission
Set submissions to submitted (incorporated)
Lock users out of confirmation page if they have no ack refs

SCRS-9388 Mini-DES Submission (already incorped)

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

SCRS-12086 uplifted dependencies and protocol changes

SCRS-12086 uplifted dependencies and protocal changes

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

SCRS-12011 modied for new build pipeline
New feature
* [X ] I've included appropriate tests with any code I've added
* [X ] I've executed the acceptance test pack locally to ensure there are no regressions
* [X ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [X ] I've run a dependency check to ensure all dependencies are up to date

SCRS-12011 modied for new build pipeline

---

app/connectors/DESConnector.scala
app/controllers/ProcessIncorporationsController.scala
app/controllers/VatRegistrationController.scala
app/services/SubmissionService.scala
it/api/ProcessIncorporationsISpec.scala
it/api/VatRegistrationBasicISpec.scala
project/AppDependencies.scala
project/plugins.sbt
test/connectors/DesConnectorSpec.scala
test/controllers/ProcessIncorporationsControllerSpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/services/SubmissionServiceSpec.scala

SCRS-12154 Handling 429 responses from DES

SCRS-12154 Handling 429 responses from DES

---

app/repositories/SequenceMongoRepository.scala
project/AppDependencies.scala
project/plugins.sbt
test/mocks/VatMocks.scala

Updated dependencies and switched to simple reactive mongo

SAR-4077 Updated dependencies

---

conf/application.conf

SAR-4360: SSLEngine exception fix

---

conf/logback.xml

SAR-5133: Config update
**Bug fix**

SAR-5133: Config update

---

app/controllers/LodgingOfficerController.scala
app/models/api/LodgingOfficer.scala
app/repositories/RegistrationMongoRepository.scala
conf/app.routes
it/controllers/LodgingOfficerControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/controllers/LodgingOfficerControllerSpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/LodgingOfficerSpec.scala
test/services/LodgingOfficerServiceSpec.scala

* [t ] I've included appropriate tests with any code I've added
* [ t] I've executed the acceptance test pack locally to ensure there are no regressions
* [t ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ t] I've run a dependency check to ensure all dependencies are up to date

SAR-5998 DOB and IV removed

---

it/api/VatRegistrationBasicISpec.scala
it/connectors/stubs/VatSubmissionStub.scala
it/itutil/IntegrationSpecBase.scala

SAR-6098 fixed it tests

---

app/models/api/Returns.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/models/ReturnsSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/VatRegistrationServiceSpec.scala
test/utils/EligibilityDataJsonUtilsSpec.scala

SAR-6152 Updated turnover estimates code

---

app/models/api/Threshold.scala
project/AppDependencies.scala
test/controllers/VatThresholdControllerSpec.scala
test/models/ThresholdSpec.scala

SAR-6163: Update Threshold model

---

app/common/LogicalGroup.scala
app/controllers/ApplicantDetailsController.scala
app/deprecated/DeprecatedConstants.scala
app/models/api/ApplicantDetails.scala
app/models/api/Name.scala
app/models/api/Validation.scala
app/models/api/VatScheme.scala
app/repositories/RegistrationMongoRepository.scala
app/services/ApplicantDetailsService.scala
app/utils/EligibilityDataJsonUtils.scala
conf/app.routes
conf/application.conf
it/controllers/ApplicantDetailsControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationCreatedMongoRepositoryISpec.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/controllers/EligibilityControllerSpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/mocks/VatMocks.scala
test/models/ApplicantDetailsSpec.scala
test/services/ApplicantDetailsServiceSpec.scala
test/utils/EligibilityDataJsonUtilsSpec.scala

SAR-6233: Refactor officer as applicant details

---

app/controllers/VatRegistrationController.scala
app/models/api/CustomerStatus.scala
app/models/api/EligibilitySubmissionData.scala
app/models/api/Returns.scala
app/models/api/Threshold.scala
app/models/api/VatScheme.scala
app/models/submission/VatSubmission.scala
app/repositories/RegistrationMongoRepository.scala
app/services/BusinessContactService.scala
app/services/EligibilityService.scala
app/services/SicAndComplianceService.scala
app/services/VatRegistrationService.scala
app/utils/EligibilityDataJsonUtils.scala
it/api/VatRegistrationCreatedBasicISpec.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationCreatedMongoRepositoryISpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/CustomerStatusSpec.scala
test/models/EligibilitySubmissionDataSpec.scala
test/models/ThresholdSpec.scala
test/models/VatSubmissionSpec.scala
test/services/BusinessContactServiceSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/SicAndComplianceServiceSpec.scala
test/services/SubmissionServiceSpec.scala
test/services/VatRegistrationCreatedServiceSpec.scala

SAR-6282 Updated handling of eligibility data

---

app/models/api/BankAccount.scala
app/models/submission/VatSubmission.scala
test/models/VatSubmissionSpec.scala

SAR-6338: Reason bank account not provided

---

it/controllers/EligibilityControllerISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/VatSubmissionSpec.scala
test/services/EligibilityServiceSpec.scala

SAR-6401 fixed failing tests

---

app/models/api/DigitalContactOptional.scala

SAR-6363: Update contact details model

---

app/models/api/BusinessContact.scala
app/models/api/ContactPreference.scala
it/controllers/BusinessContactControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala

added contact preference to submission

---

app/models/api/Returns.scala
app/models/submission/VatSubmission.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/repository/RegistrationCreatedMongoRepositoryISpec.scala
test/connectors/DesConnectorSpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/ReturnsSpec.scala
test/models/VatSubmissionSpec.scala

added zeroRatedSupplies to return and submission models

---

app/services/EligibilityService.scala
test/services/EligibilityServiceSpec.scala

SAR-6436 ensured failures to store elig data become exceptions

---

app/helpers/ApplicantDetailsHelper.scala
app/models/api/ApplicantDetails.scala
app/models/api/DigitalContact.scala
app/models/submission/IdVerificationStatus.scala
app/models/submission/PartyType.scala
it/controllers/BusinessContactControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/VatDigitalContactSpec.scala

initial submission correction

---

app/helpers/ApplicantDetailsHelper.scala
app/models/api/ApplicantDetails.scala
app/models/api/ComplianceLabour.scala
app/models/api/DigitalContactOptional.scala
app/models/api/EligibilitySubmissionData.scala
app/models/api/Returns.scala
app/models/api/SicAndCompliance.scala
app/models/api/VatScheme.scala
app/models/submission/DeclarationCapacity.scala
app/models/submission/VatSubmission.scala
app/services/ApplicantDetailsService.scala
app/services/SubmissionService.scala
app/utils/JsonUtilities.scala
it/controllers/EligibilityControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/connectors/DesConnectorSpec.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/EligibilitySubmissionDataSpec.scala
test/models/ReturnsSpec.scala
test/models/VatSubmissionSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/VatRegistrationCreatedServiceSpec.scala

SAR-6448: Add missing data to submission

---

app/models/api/Address.scala
it/controllers/BusinessContactControllerISpec.scala
it/controllers/test/StubDesSubmissionControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/repository/RegistrationCreatedMongoRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala

SAR-6448: Store country model in backend

---

app/config/BackendConfig.scala
app/models/api/Address.scala
app/models/api/FlatRateScheme.scala
app/models/api/Name.scala
app/models/monitoring/RegistrationSubmissionAuditing.scala
app/services/SubmissionService.scala
app/services/monitoring/AuditService.scala
app/utils/JsonUtilities.scala
it/api/VatRegistrationCreatedBasicISpec.scala
it/itutil/ITFixtures.scala
it/itutil/IntegrationStubbing.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/mocks/VatMocks.scala
test/mocks/monitoring/MockAuditService.scala
test/services/SubmissionServiceSpec.scala
test/services/monitoring/AuditServiceSpec.scala

SAR-6445 Added a submission audit and auditing service

---

app/models/monitoring/RegistrationSubmissionAuditing.scala

SAR-6505 Updated the audit to fix minor issues

---

app/models/monitoring/RegistrationSubmissionAuditing.scala

SAR-6505 fixed bank details

---

app/models/api/CustomerStatus.scala
test/models/CustomerStatusSpec.scala

SAR-6511 update to eligibility reads

---

app/repositories/RegistrationMongoRepository.scala

Updated internalId retrieval

---

app/config/BackendConfig.scala
app/controllers/TrafficManagementController.scala
app/controllers/VatRegistrationController.scala
app/featureswitch/core/config/FeatureSwitchingModule.scala
app/repositories/trafficmanagement/DailyQuotaRepository.scala
app/services/NewRegistrationService.scala
app/services/TrafficManagementService.scala
conf/app.routes
conf/application.conf
it/controllers/TrafficManagementControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/IntegrationSpecBase.scala
it/repository/DailyQuotaRepositoryISpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/mocks/MockDailyQuotaRepository.scala
test/mocks/MockNewRegistrationService.scala
test/mocks/MockTrafficManagementRepository.scala
test/mocks/MockTrafficManagementService.scala
test/services/NewRegistrationServiceSpec.scala
test/services/TrafficManagementServiceSpec.scala

SAR-6508: Create separate traffic management API

---

app/connectors/VatSubmissionConnector.scala
app/services/SubmissionService.scala
test/services/SubmissionServiceSpec.scala

SAR-6582: Update header to include credential ID to submission call

---

app/models/api/BankAccount.scala
app/models/api/SicAndCompliance.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatSubmissionFixture.scala

SAR-6588 Payload fix

---

conf/application.conf

SAR-6559 - Fix local config

---

app/services/SubmissionService.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/IntegrationStubbing.scala

SAR-6589: Update logs and add IT tests for submission

---

app/helpers/ApplicantDetailsHelper.scala
app/models/submission/IdVerificationStatus.scala

SAR-6606 updated BvUnchallenged status to map to verification failed

---

app/config/BackendConfig.scala
app/controllers/TrafficManagementController.scala
app/services/TrafficManagementService.scala
conf/app.routes
it/controllers/TrafficManagementControllerISpec.scala
test/services/TrafficManagementServiceSpec.scala

SAR-6605: add upsertRegInfo to TrafficManagementService

---

app/models/api/FlatRateScheme.scala
it/controllers/FlatRateSchemeControllerISpec.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/FlatRateSchemeSpec.scala

SAR-6600 - Update flat Rate Scheme submission to send correct data

---

app/repositories/trafficmanagement/TrafficManagementRepository.scala
app/services/SubmissionService.scala
app/services/TrafficManagementService.scala
test/mocks/MockTrafficManagementService.scala
test/mocks/VatMocks.scala
test/services/SubmissionServiceSpec.scala

SAR-6642: Update traffic management on submission

---

app/controllers/test/UpdateTrafficManagementController.scala
conf/test.routes
it/controllers/test/UpdateTrafficManagementControllerISpec.scala
it/repository/TrafficManagementRepositoryISpec.scala

SAR-6646: Add API to reset traffic management quota

---

app/models/api/FlatRateScheme.scala
app/models/submission/VatSubmission.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/FlatRateSchemeSpec.scala

SAR-6648 Updated the FRS model to allow FRSCategory to be None

---

app/models/api/SicAndCompliance.scala
it/controllers/SicAndComplianceControllerISpec.scala
it/repository/RegistrationCreatedMongoRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/SicAndComplianceSpec.scala
test/models/VatSubmissionSpec.scala

SAR-6733 Fixed main sic code duplication in submissions

---

app/controllers/test/StubVatSubmissionController.scala
app/models/api/ApplicantDetails.scala
app/models/api/BankAccount.scala
app/models/api/FlatRateScheme.scala
app/models/api/Returns.scala
app/models/api/SicAndCompliance.scala
app/models/monitoring/RegistrationSubmissionAuditing.scala
app/models/submission/VatSubmission.scala
test/fixtures/VatSubmissionFixture.scala
test/models/ReturnsSpec.scala
test/models/VatSubmissionSpec.scala

SAR-6734 Updated the submission to always contain relevantDate

---

app/models/api/ComplianceLabour.scala
it/controllers/SicAndComplianceControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/SicAndComplianceSpec.scala

Unit and IT tests pass locally

SAR-6768: Add FS and update formats for new questions

---

app/controllers/VatRegistrationController.scala
app/models/ElementPath.scala
app/models/api/VatScheme.scala
app/models/monitoring/RegistrationSubmissionAuditing.scala
app/models/submission/VatSubmission.scala
app/repositories/RegistrationMongoRepository.scala
app/services/VatRegistrationService.scala
conf/app.routes
it/controllers/VatRegistrationControllerISpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/VatSubmissionSpec.scala
test/services/VatRegistrationCreatedServiceSpec.scala

SAR-6842 - create API to store response from honesty declaration

---

app/helpers/ApplicantDetailsHelper.scala
app/models/api/ApplicantDetails.scala
app/models/api/BusinessRegistrationStatus.scala
app/models/api/BusinessVerificationStatus.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/models/ApplicantDetailsSpec.scala

SAR-6782 Updated handling of incorp entity responses

---

app/services/submission/CustomerIdentificationBlockBuilder.scala
test/fixtures/VatRegistrationFixture.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

SAR-6905: Create new CustomerIdentification service

---

app/services/submission/CustomerIdentificationBlockBuilder.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

SAR-6905MH: Added tests/improved error messages

---

app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/PeriodsBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
app/services/submission/SubmissionService.scala
it/services/submission/SubmissionPayloadBuilderISpec.scala
test/mocks/MockRegistrationRepository.scala
test/services/submission/PeriodsBlockBuilderSpec.scala

SAR-6908: Periods section builder

---

app/services/submission/ContactBlockBuilder.scala
project/AppDependencies.scala
project/build.properties
test/fixtures/VatRegistrationFixture.scala
test/services/submission/ContactBlockBuilderSpec.scala

SAR-6906: Create new service to create contact block

---

app/services/submission/BankDetailsBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
it/services/submission/SubmissionPayloadBuilderISpec.scala
test/services/submission/BankDetailsBlockBuilderSpec.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/buildermocks/MockBankDetailsBlockBuilder.scala

SAR-6909: Create new BankDetailsBlockBuilder

---

app/models/api/ComplianceLabour.scala
app/models/api/SicAndCompliance.scala
app/services/submission/SubmissionPayloadBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/services/submission/SubmissionPayloadBuilderISpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala
test/services/submission/buildermocks/MockSubscriptionBlockBuilder.scala

SAR-6907 added SubscriptionBlockBuilderService

---

app/services/submission/DeclarationBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
it/services/submission/SubmissionPayloadBuilderISpec.scala
test/services/submission/DeclarationBlockBuilderSpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/buildermocks/MockDeclarationBlockBuilder.scala

SAR-6911: Declaration block builder

---

app/services/submission/SubscriptionBlockBuilder.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-7025 Update the builder to treat FRS block as optional

---

app/controllers/test/StubVatSubmissionController.scala
conf/vat-registration-api-schema.yaml
it/controllers/FlatRateSchemeControllerISpec.scala
it/itutil/ITFixtures.scala
project/AppDependencies.scala

Added API schema validation to the stub vat submission controller

---

app/services/monitoring/ComplianceBlockBuilder.scala
test/services/monitoring/ComplianceBlockBuilderSpec.scala

SAR-7134 Created audit ComplianceBlockBuilder

---

app/services/monitoring/BankAuditBlockBuilder.scala
test/services/monitoring/BankAuditBlockBuilderSpec.scala

SAR-7119 Create audit json builder and BankDetails Block

---

app/services/monitoring/BankAuditBlockBuilder.scala
app/services/monitoring/ComplianceBlockBuilder.scala
app/services/monitoring/SubscriptionBlockBuilder.scala
test/services/monitoring/SubscriptionBlockBuilderSpec.scala

SAR-7145 added audit SubscriptionBlockBuilder

---

app/services/monitoring/DeclarationBlockBuilder.scala
test/services/monitoring/DeclarationBlockBuilderSpec.scala

SAR-7147 added DeclarationBlockBuilder

---

app/services/monitoring/BankAuditBlockBuilder.scala
app/services/monitoring/ContactAuditBlockBuilder.scala
app/services/monitoring/PeriodsAuditBlockBuilder.scala
test/services/monitoring/BankAuditBlockBuilderSpec.scala
test/services/monitoring/PeriodsAuditBlockBuilderSpec.scala

SAR-7146 Create periods Audit block builder

---

app/models/api/EligibilitySubmissionData.scala
app/services/submission/SubscriptionBlockBuilder.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-7211 updated the relevant date to not add 2 months on backward look

---

project/AppDependencies.scala

Bootstrap and reactivemongo uplift

---

app/models/api/AnnualAccountingScheme.scala
app/models/api/AnnualStagger.scala
app/models/api/PaymentFrequency.scala
app/models/api/PaymentMethod.scala
app/models/api/VatScheme.scala
app/models/monitoring/RegistrationSubmissionAuditing.scala
app/repositories/RegistrationMongoRepository.scala
app/services/monitoring/AnnualAccountingAuditBlockBuilder.scala
app/services/monitoring/SubmissionAuditBlockBuilder.scala
app/services/submission/AnnualAccountingBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
it/controllers/AnnualAccountingSchemeControllerISpec.scala
it/controllers/BusinessContactControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/SubmissionAuditFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/fixtures/VatSubmissionFixture.scala
test/services/monitoring/AnnualAccountingAuditBlockBuilderSpec.scala
test/services/submission/AnnualAccountingBlockBuilderSpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/buildermocks/MockAnnualAccountingBlockBuilder.scala

SAR-7470 Updated submission for AAS Block

---

app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/services/monitoring/CustomerIdentificationBlockBuilder.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ApplicantDetailsSpec.scala

SAR-7672 updated the SoleTrader model to better match data coming from STI

---

it/controllers/VatRegistrationControllerISpec.scala
it/controllers/test/StubVatSubmissionControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala

SAR-7723 added tests for sole trader flow

---

app/services/submission/CustomerIdentificationBlockBuilder.scala
it/itutil/ITVatSubmissionFixture.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

SAR-7752 don't submit shortOrgName when safeid is present

---

app/config/BackendConfig.scala
app/controllers/TrafficManagementController.scala
app/controllers/test/UpdateTrafficManagementController.scala
app/models/api/DailyQuota.scala
app/repositories/trafficmanagement/DailyQuotaRepository.scala
app/services/TrafficManagementService.scala
conf/application.conf
it/controllers/TrafficManagementControllerISpec.scala
it/controllers/test/UpdateTrafficManagementControllerISpec.scala
it/itutil/IntegrationSpecBase.scala
it/repository/DailyQuotaRepositoryISpec.scala
test/mocks/MockDailyQuotaRepository.scala
test/mocks/MockTrafficManagementService.scala
test/services/TrafficManagementServiceSpec.scala
test/utils/FakeTimeMachine.scala

The quotas I've added to the config are for testing purposes only - the real quotas will need to be procured from the business.

SAR-7750: Manage traffic by entity type

---

app/repositories/trafficmanagement/DailyQuotaRepository.scala

Removed the daily quota index reset now that it has run in prod

---

app/models/api/EligibilitySubmissionData.scala
app/models/submission/PartyType.scala
it/controllers/EligibilityControllerISpec.scala
test/models/EligibilitySubmissionDataSpec.scala
test/services/EligibilityServiceSpec.scala

SAR-7858 updated how partytype is parsed from EL

---

app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/services/monitoring/CustomerIdentificationBlockBuilder.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ApplicantDetailsSpec.scala

SAR-7855 Added general partnership to business entity models

---

app/services/submission/CustomerIdentificationBlockBuilder.scala
app/utils/StringNormaliser.scala
test/utils/StringNormaliserSpec.scala

SAR-7869 Added a string normaliser to clean up company names

---

app/controllers/PartnersController.scala
app/models/api/Partner.scala
app/models/api/VatScheme.scala
app/repositories/RegistrationMongoRepository.scala
app/services/PartnersService.scala
conf/app.routes
it/controllers/PartnersControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/api/PartnerSpec.scala
test/services/PartnersServiceSpec.scala

SAR-7875: Partners APIs

---

app/models/BusinessEntity.scala
app/models/submission/EntitiesArrayType.scala
app/services/PartnersService.scala
app/services/monitoring/CustomerIdentificationBlockBuilder.scala
app/services/submission/EntitiesBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/submission/EntitiesArrayTypeSpec.scala
test/services/PartnersServiceSpec.scala
test/services/monitoring/buildermocks/MockEntitiesBlockBuilder.scala
test/services/submission/EntitiesBlockBuilderSpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/buildermocks/MockPartnersService.scala

SAR-7856: Entity block submission builder

---

app/models/IncorporatedEntity.scala
app/models/api/ApplicantDetails.scala
app/models/api/Partner.scala
app/models/api/VatScheme.scala
app/models/monitoring/SubmissionAuditModel.scala
app/services/monitoring/CustomerIdentificationBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/itutil/ITFixtures.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/monitoring/SubmissionAuditModelSpec.scala

SAR-7917 Renamed business entity model to more generic name

---

app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/models/api/Partner.scala
app/models/api/VatScheme.scala

SAR-7917 Fix name of Business Entity model

---

app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/models/api/Partner.scala
app/services/monitoring/CustomerIdentificationBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ApplicantDetailsSpec.scala
test/models/api/PartnerSpec.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

SAR-7926 added Trust logic

---

app/controllers/ApplicantDetailsController.scala
app/controllers/VatRegistrationController.scala
app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/models/api/VatScheme.scala
app/repositories/RegistrationMongoRepository.scala
app/services/ApplicantDetailsService.scala
app/services/VatRegistrationService.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/ApplicantDetailsControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/IntegrationSpecBase.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/controllers/BusinessContactControllerSpec.scala
test/controllers/EligibilityControllerSpec.scala
test/controllers/FlatRateSchemeControllerSpec.scala
test/controllers/ReturnsControllerSpec.scala
test/controllers/SicAndComplianceControllerSpec.scala
test/controllers/TradingDetailsControllerSpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ApplicantDetailsSpec.scala
test/models/monitoring/SubmissionAuditModelSpec.scala
test/services/ApplicantDetailsServiceSpec.scala
test/services/VatRegistrationCreatedServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-8012: Update models to reflect FE changes

---

app/models/BusinessEntity.scala
app/models/api/ApplicantDetails.scala
app/models/api/Partner.scala
app/models/api/TransactorDetails.scala
app/models/monitoring/SubmissionAuditModel.scala
app/models/submission/PartyType.scala
app/services/EligibilityService.scala
app/services/monitoring/CustomerIdentificationAuditBlockBuilder.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/itutil/ITFixtures.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ApplicantDetailsSpec.scala
test/services/EligibilityServiceSpec.scala

SAR-8090 updated soletrader model to allow trn and updated eligibility data store

---

app/services/NonRepudiationService.scala
app/services/submission/SubmissionService.scala
test/services/NonRepudiationServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-8151: Update NRS search key to formBundleId

---

app/featureswitch/core/config/FeatureSwitchingModule.scala
app/services/submission/SubmissionService.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-8149: Removed Use CYA HTML as payload for NRS feature switch and updated code & tests

---

app/config/BackendConfig.scala
app/services/TrafficManagementService.scala
conf/application.conf

SAR-8202 Updated TM to handle NETP

---

app/controllers/AttachmentsController.scala
app/models/api/AttachmentType.scala
app/services/AttachmentsService.scala
conf/app.routes
it/controllers/AttachmentsControllerISpec.scala
it/itutil/IntegrationSpecBase.scala
test/models/api/AttachmentTypeSpec.scala

SAR-8208 Added an attachments api with logic for NETP

---

app/models/api/EligibilitySubmissionData.scala
app/models/api/Threshold.scala
app/models/monitoring/SubmissionAuditModel.scala
app/services/monitoring/AnnualAccountingAuditBlockBuilder.scala
app/services/submission/AnnualAccountingBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
test/models/ThresholdSpec.scala

SAR-8180 Updated eligibility controller to handle overseas payloads

---

app/models/api/Address.scala
app/services/monitoring/ContactAuditBlockBuilder.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/ContactBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
app/services/submission/EntitiesBlockBuilder.scala
it/controllers/BusinessContactControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/SubmissionAuditFixture.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/services/monitoring/ContactAuditBlockBuilderSpec.scala

SAR-8211: Updated Address model and tests to add line 5 and make line 2 opt

---

app/controllers/test/StubVatSubmissionController.scala
app/models/monitoring/SubmissionAuditModel.scala
app/services/AttachmentsService.scala
app/services/monitoring/BankAuditBlockBuilder.scala
app/services/monitoring/SubmissionAuditBlockBuilder.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/AdminBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
conf/logback-test.xml
conf/vat-registration-api-schema.yaml
it/controllers/VatRegistrationControllerISpec.scala
it/controllers/test/StubVatSubmissionControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/mocks/MockAttachmentsService.scala
test/services/submission/AdminBlockBuilderSpec.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-8256 Updated the submission to handle NETP

---

app/models/api/ApplicantDetails.scala
app/models/api/TransactorDetails.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala

SAR-8305 Updated transactor details to handle trn

---

app/models/api/TransactorDetails.scala

Fixed transactor details to prevent users from failing with old data

---

app/models/api/returns/NIPCompliance.scala
app/models/api/returns/Returns.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/ReturnsControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/SubmissionAuditFixture.scala
it/repository/RegistrationMongoRepositoryISpec.scala
test/controllers/ReturnsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/ReturnsSpec.scala
test/services/monitoring/SubscriptionAuditBlockBuilderSpec.scala
test/services/submission/PeriodsBlockBuilderSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-8283 Added northern ireland protocol to the vatscheme and submission

---

app/controllers/AttachmentsController.scala
app/models/api/AttachmentType.scala
app/models/api/Attachments.scala
app/models/api/VatScheme.scala
app/services/AttachmentsService.scala
conf/app.routes
it/controllers/AttachmentsControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala
test/mocks/MockRegistrationRepository.scala
test/services/AttachmentsServiceSpec.scala
test/services/submission/AdminBlockBuilderSpec.scala

SAR-8362: API to store attachment method

---

app/config/BackendConfig.scala
app/models/BusinessEntity.scala
app/models/monitoring/SubmissionAuditModel.scala
app/models/submission/RoleInBusiness.scala
app/services/AttachmentsService.scala
app/services/TrafficManagementService.scala
app/services/monitoring/BankAuditBlockBuilder.scala
app/services/submission/AdminBlockBuilder.scala
app/services/submission/BankDetailsBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
conf/application.conf
it/controllers/AttachmentsControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/controllers/test/StubVatSubmissionControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/services/ApplicantDetailsServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-8375 Updated the backend to support non uk companies

---

app/models/api/EligibilitySubmissionData.scala
app/services/EligibilityService.scala
it/controllers/EligibilityControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/models/EligibilitySubmissionDataSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/VatRegistrationCreatedServiceSpec.scala

SAR-8469 Updated the backend to parse out the transactor boolean from eligibility payload

---

app/models/api/TransactorDetails.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala

SAR-8670 Updated declaration capacity to handle Other

---

app/models/api/TransactorDetails.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala

**New feature** (delete as appropriate)

SAR-8712: emailVerified field added in TransactorDetails

---

app/controllers/TrafficManagementController.scala
app/repositories/trafficmanagement/TrafficManagementRepository.scala
app/services/TrafficManagementService.scala
conf/app.routes
it/controllers/TrafficManagementControllerISpec.scala
it/repository/TrafficManagementRepositoryISpec.scala
test/mocks/MockTrafficManagementRepository.scala
test/services/TrafficManagementServiceSpec.scala

SAR-8738: RegID based traffic management API

---

app/featureswitch/core/config/FeatureSwitchingModule.scala
app/models/api/TradingDetails.scala
app/services/monitoring/CustomerIdentificationAuditBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
it/repository/VatSchemeRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/TradingDetailsSpec.scala

SAR-8728 Updated the tradingDetails model and submission builder to handle new short org name logic

---

app/config/BackendConfig.scala
app/services/TrafficManagementService.scala
conf/application.conf

Add missing trust & unincorp TM config

---

app/repositories/trafficmanagement/TrafficManagementRepository.scala

SAR-8738-b: Update indexes on TM to avoid duplicate keys

---

app/models/api/BankAccount.scala
app/models/api/BankAccountDetailsStatus.scala
app/services/monitoring/BankAuditBlockBuilder.scala
app/services/submission/BankDetailsBlockBuilder.scala
it/itutil/ITFixtures.scala
it/repository/VatSchemeRepositoryISpec.scala
it/services/SubmissionAuditBlockBuilderISpec.scala
test/controllers/VatRegistrationCreatedControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/BankAccountSpec.scala
test/services/monitoring/BankAuditBlockBuilderSpec.scala
test/services/submission/BankDetailsBlockBuilderSpec.scala

SAR-8751 Updated BankAccountDetails to store validation status and submit bankDetailsNotValid on indeterminate status

---

app/controllers/test/DeleteAllRegistrationsController.scala
conf/test.routes

SAR-8740: Test only 'delete registrations' route

---

app/models/BusinessEntity.scala
it/itutil/ITFixtures.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

SAR-8769 Updated the business entity models to support missing BV status

---

app/models/api/VatScheme.scala
app/repositories/VatSchemeRepository.scala
it/controllers/ReturnsControllerISpec.scala
it/controllers/registrations/RegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/RegistrationRepositoryISpec.scala
it/repository/VatSchemeRepositoryISpec.scala

SAR-8814: Add createdDate field to VatScheme model

---

app/models/api/Partner.scala

SAR-8826 Updated partner format to handle more partytypes

---

app/controllers/TrafficManagementController.scala
app/repositories/trafficmanagement/TrafficManagementRepository.scala
app/services/TrafficManagementService.scala
conf/app.routes
it/controllers/TrafficManagementControllerISpec.scala
it/repository/TrafficManagementRepositoryISpec.scala
test/mocks/MockTrafficManagementRepository.scala
test/mocks/MockTrafficManagementService.scala
test/services/TrafficManagementServiceSpec.scala

SAR-8741: Remove old TM API

---

app/services/submission/EntitiesBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/services/submission/EntitiesBlockBuilderSpec.scala

SAR-8773 updated partner block builder

---

app/models/monitoring/SubmissionAuditModel.scala
app/services/monitoring/EntitiesAuditBlockBuilder.scala
app/services/monitoring/SubmissionAuditBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala
test/services/submission/EntitiesBlockBuilderSpec.scala

SAR-8939 Updated submission to support groups (without VAT51 attachment)

---

app/services/AttachmentsService.scala
test/services/AttachmentsServiceSpec.scala

SAR-8950 Updated the AttachmentsService to require VAT51 for groups

---

app/models/api/SicAndCompliance.scala
app/models/api/SicCode.scala
app/repositories/VatSchemeRepository.scala
app/services/AttachmentsService.scala
test/controllers/SicAndComplianceControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/services/AttachmentsServiceSpec.scala
test/services/SicAndComplianceServiceSpec.scala
test/services/monitoring/ComplianceBlockBuilderSpec.scala
test/services/submission/ComplianceBlockBuilderSpec.scala

SAR-9027 added hasLandAndProperty boolean and set up attachments to handle VAT5L

---

app/models/api/PersonalDetails.scala
app/models/api/TransactorDetails.scala
app/models/submission/IdType.scala
app/services/monitoring/CustomerIdentificationAuditBlockBuilder.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
app/utils/JsonUtils.scala
build.sbt
conf/logback.xml
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
test/controllers/ApplicantDetailsControllerSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/services/RegistrationServiceSpec.scala
test/services/monitoring/DeclarationAuditBlockBuilderSpec.scala

SAR-9073: Agent specific transactor model  & submission changes

---

app/models/RegistrationReason.scala
app/services/EligibilityService.scala
app/services/submission/SubmissionService.scala
test/mocks/MockAttachmentsService.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-9079 Added eligibility payload and submission logs

---

app/models/TogcCole.scala
app/models/api/EligibilitySubmissionData.scala
app/services/EligibilityService.scala
app/services/monitoring/AnnualAccountingAuditBlockBuilder.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/models/EligibilitySubmissionDataSpec.scala

SAR-9094 Added TOGC/COLE data to the eligibility block and submission

---

app/config/BackendConfig.scala
app/connectors/SdesConnector.scala
app/controllers/SdesController.scala
app/models/sdes/SdesNotification.scala
app/models/sdes/SdesNotificationResult.scala
app/repositories/UpscanMongoRepository.scala
app/services/SdesService.scala
conf/application.conf
it/connectors/SdesConnectorISpec.scala
it/connectors/stubs/SdesNotifyStub.scala
it/itutil/IntegrationSpecBase.scala
test/mocks/MockSdesConnector.scala
test/services/SdesServiceSpec.scala

SAR-9260 Set up integration with SDES Notification

---

app/config/BackendConfig.scala
app/connectors/NonRepudiationConnector.scala
app/controllers/SdesController.scala
app/controllers/test/StubNrsController.scala
app/controllers/test/StubSdesController.scala
app/models/nonrepudiation/NonRepudiationAttachment.scala
app/models/nonrepudiation/NonRepudiationAttachmentResult.scala
app/models/sdes/Property.scala
app/models/sdes/SdesCallback.scala
app/models/sdes/SdesNotification.scala
app/services/SdesService.scala
conf/app.routes
conf/test.routes
it/connectors/NonRepudiationConnectorISpec.scala
it/connectors/SdesConnectorISpec.scala
it/connectors/stubs/NonRepudiationStub.scala
it/controllers/SdesControllerISpec.scala
test/services/SdesServiceSpec.scala

SAR-9278 Set up SDES callback and NRS call, set up stubs, tests

---

app/connectors/NonRepudiationConnector.scala
app/models/nonrepudiation/NonRepudiationMetadata.scala
app/models/sdes/SdesAuditing.scala
app/models/sdes/SdesCallback.scala
app/services/NonRepudiationService.scala
app/services/SdesService.scala
app/services/submission/SubmissionService.scala
app/utils/JsonUtilities.scala
it/connectors/NonRepudiationConnectorISpec.scala
it/connectors/SdesConnectorISpec.scala
it/connectors/stubs/SdesNotifyStub.scala
it/controllers/SdesControllerISpec.scala
it/controllers/UpscanControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/FakeIdGenerator.scala
it/itutil/ITFixtures.scala
it/itutil/IntegrationSpecBase.scala
it/repository/VatSchemeRepositoryISpec.scala
it/services/SubmissionAuditBlockBuilderISpec.scala
test/mocks/MockSdesService.scala
test/services/NonRepudiationServiceSpec.scala
test/services/SdesServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-9279 set up SDES in the submission logic for digital attachments, set up SDES notification failure audit

---

app/models/api/TradingDetails.scala
it/itutil/ITFixtures.scala
it/repository/VatSchemeRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/TradingDetailsSpec.scala

SAR-9308 Updated trading details to support new tradeVatGoodsOutsideUk field

---

app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala

SAR-9363 updated submission to avoid sending a duplicated date for mandatory flows

---

app/models/api/SicAndCompliance.scala
test/models/SicAndComplianceSpec.scala

SAR-9381 added support for OBI page

---

app/controllers/VatRegistrationController.scala
app/controllers/test/RetrieveVatSubmissionController.scala
app/models/api/OtherBusinessInvolvement.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/SubmissionPayloadBuilder.scala
app/services/submission/SubmissionService.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/test/RetrieveVatSubmissionControllerISpec.scala
it/itutil/SubmissionAuditFixture.scala
it/services/SubmissionAuditBlockBuilderISpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/services/submission/SubmissionPayloadBuilderSpec.scala
test/services/submission/SubmissionServiceSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala
test/services/submission/buildermocks/MockSubmissionPayloadBuilder.scala
test/services/submission/buildermocks/MockSubscriptionBlockBuilder.scala

SAR-9425 Added OBI block to the submission builder

---

app/controllers/AttachmentsController.scala
app/controllers/UpscanController.scala
app/models/api/AttachmentType.scala
app/models/api/UpscanCreate.scala
app/models/api/UpscanDetails.scala
app/repositories/UpscanMongoRepository.scala
app/services/AttachmentsService.scala
app/services/SdesService.scala
app/services/UpscanService.scala
conf/app.routes
it/controllers/AttachmentsControllerISpec.scala
it/controllers/UpscanControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/UpscanMongoRepositoryISpec.scala
test/mocks/MockUpscanMongoRepository.scala
test/services/AttachmentsServiceSpec.scala
test/services/SdesServiceSpec.scala
test/services/UpscanServiceSpec.scala

SAR-9486 Added upscan delete api, added incomplete attachments api, updated create upscan api

---

app/featureswitch/core/config/FeatureSwitchingModule.scala
app/models/api/PersonalDetails.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala

[SAR-9123] [22nd MARCH RELEASE] - Drop TRN from Applicant block on submission

SAR-9320 skip trn while submitting

---

app/controllers/registrations/RegistrationSectionController.scala

[SAR-9462] [VRS] Update get registration and get section (for bank details) to decrypt bank details
**Bug fix**

SAR-9462 remove unnecessary comma that failed the build

---

app/services/monitoring/ContactAuditBlockBuilder.scala
app/services/submission/ContactBlockBuilder.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/SubmissionAuditFixture.scala
test/services/monitoring/ContactAuditBlockBuilderSpec.scala
test/services/submission/ContactBlockBuilderSpec.scala

SAR-9531 Updated emailVerified logic

---

app/connectors/SdesConnector.scala
app/controllers/test/StubSdesController.scala
app/httpparsers/SdesNotificationHttpParser.scala
app/models/sdes/Property.scala
app/models/sdes/SdesAuditing.scala
app/models/sdes/SdesCallback.scala
app/models/sdes/SdesNotification.scala
app/models/sdes/SdesNotificationResult.scala
app/services/SdesService.scala
it/connectors/SdesConnectorISpec.scala
it/itutil/ITFixtures.scala
test/mocks/MockSdesService.scala
test/services/SdesServiceSpec.scala

SAR-9597 Added an SDES file submission audit

---

app/models/nonrepudiation/NonRepudiationAuditing.scala
app/services/SdesService.scala
test/helpers/VatRegSpec.scala
test/services/SdesServiceSpec.scala

SAR-9600 added attachment NRS success and failure audits

---

app/models/sdes/SdesAuditing.scala
app/services/SdesService.scala
app/services/submission/SubmissionService.scala
test/mocks/MockSdesService.scala
test/services/SdesServiceSpec.scala

`informationType` field also agreed to be added on 20/05/22.
Output from Wireshark:
```
{
"auditSource": "vat-registration",
"auditType": "SDESFileSubmission",
"eventId": "3b193032-4535-431f-a1af-4ba0e5072524",
"tags": {
"clientIP": "-",
"path": "/vatreg/6ca7484a-02f2-44aa-a80d-737c6f319f83/submit-registration",
"X-Session-ID": "session-69465cd9-b193-4d30-9660-958a014252f0",
"Akamai-Reputation": "-",
"X-Request-ID": "govuk-tax-79021850-4f2b-4b67-bb1b-cdeb14501d26",
"deviceID": "mdtpdi#b9abae30-c7d4-4da4-8fef-4c48c7a8caed#1615983629541_DKHYQENte+q0McKvJtydHQ==",
"clientPort": "-",
"transactionName": "SDESFileSubmission"
},
"detail": {
"authProviderId": "4341662521702639",
"informationType": "S18",
"file": {
"recipientOrSender": "123456789012",
"name": "VAT2.testFile",
"location": …
```

SAR-9653: Add authProviderId to SDES audit

---

app/featureswitch/core/config/FeatureSwitchingModule.scala
app/services/monitoring/CustomerIdentificationAuditBlockBuilder.scala
app/services/monitoring/EntitiesAuditBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
app/services/submission/EntitiesBlockBuilder.scala
conf/vat-registration-api-schema.yaml
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala
it/itutil/SubmissionAuditFixture.scala
test/services/monitoring/CustomerIdentificationAuditBlockBuilderSpec.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala
test/services/submission/EntitiesBlockBuilderSpec.scala

Remove shortOrgName feature switch

SAR-9774 | Remove shortOrgName feature switch

---

app/controllers/test/DeleteAllRegistrationsController.scala
app/models/api/VatScheme.scala
app/repositories/VatSchemeRepository.scala
conf/application.conf
it/controllers/AttachmentsControllerISpec.scala
it/controllers/FlatRateSchemeControllerISpec.scala
it/controllers/NrsSubmissionPayloadControllerISpec.scala
it/controllers/UpscanControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/controllers/registrations/RegistrationControllerISpec.scala
it/controllers/test/RetrieveVatSubmissionControllerISpec.scala
it/itutil/IntegrationSpecBase.scala
it/repository/RegistrationRepositoryISpec.scala
it/repository/VatSchemeRepositoryISpec.scala
project/AppDependencies.scala

SAR-9867: Migrate VatSchemeRepository to hmrc-mongo

---

app/controllers/test/UpdateTrafficManagementController.scala
app/models/api/Partner.scala
app/models/monitoring/SubmissionAuditModel.scala
app/repositories/UpscanMongoRepository.scala
app/repositories/trafficmanagement/DailyQuotaRepository.scala
app/repositories/trafficmanagement/TrafficManagementRepository.scala
app/services/TrafficManagementService.scala
conf/application.conf
it/controllers/AttachmentsControllerISpec.scala
it/controllers/FlatRateSchemeControllerISpec.scala
it/controllers/TrafficManagementControllerISpec.scala
it/controllers/UpscanControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/controllers/test/UpdateTrafficManagementControllerISpec.scala
it/itutil/IntegrationSpecBase.scala
it/itutil/IntegrationStubbing.scala
it/repository/DailyQuotaRepositoryISpec.scala
it/repository/RegistrationRepositoryISpec.scala
it/repository/TrafficManagementRepositoryISpec.scala
it/repository/UpscanMongoRepositoryISpec.scala
project/AppDependencies.scala
test/mocks/MockUpscanMongoRepository.scala
test/services/EligibilityServiceSpec.scala
test/services/UpscanServiceSpec.scala

SAR-9865 Migrate DailyQuotaRepository, TrafficManagementRepository and UpscanMongoRepository to hmrc-mongo

SAR-9865 Migrate DailyQuotaRepository, TrafficManagementRepository and UpscanMongoRepository to hmrc-mongo

---

app/controllers/test/DeleteAllRegistrationsController.scala
app/models/api/VatScheme.scala
app/repositories/VatSchemeRepository.scala
conf/application.conf
it/controllers/NrsSubmissionPayloadControllerISpec.scala
it/controllers/test/RetrieveVatSubmissionControllerISpec.scala
it/itutil/IntegrationStubbing.scala
it/itutil/MongoBaseSpec.scala
it/repository/VatSchemeRepositoryISpec.scala
project/AppDependencies.scala

SAR-9950 Remove reactive mongo dependencies

SAR-9950 Remove reactive mongo dependencies

---

app/repositories/VatSchemeRepository.scala

[SAR-9903](https://jira.tools.tax.service.gov.uk/browse/SAR-9903)

Revert "SAR-9902 | runOnce method to generate vat-application block for old vat-schema journeys"

---

app/controllers/registrations/RegistrationController.scala
app/repositories/VatSchemeRepository.scala
app/services/RegistrationService.scala
it/controllers/registrations/RegistrationControllerISpec.scala
it/repository/RegistrationRepositoryISpec.scala
test/mocks/MockVatSchemeRepository.scala
test/services/RegistrationServiceSpec.scala

Fix PUT /registrations method decryption issue

---

app/config/BackendConfig.scala
app/connectors/SdesConnector.scala
app/services/SdesService.scala
conf/application.conf
test/services/SdesServiceSpec.scala

SAR-9960 Updated SDES payload and added auth header

---

app/models/api/RegistrationInformation.scala
app/repositories/trafficmanagement/TrafficManagementRepository.scala
app/services/TrafficManagementService.scala
it/controllers/TrafficManagementControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/TrafficManagementRepositoryISpec.scala
test/mocks/MockTrafficManagementRepository.scala
test/services/RegistrationServiceSpec.scala
test/services/TrafficManagementServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-9974: Changed lastModified field in TrafficManagementRepository from LocalDate to LocalDateTime and updated tests

---

app/repositories/trafficmanagement/TrafficManagementRepository.scala

SAR-9974b: Removed runOnce method for updating date formats for regInfo entries

---

app/controllers/VatRegistrationController.scala

Updated a handled exception to not be thrown and logged

---

app/controllers/registrations/RegistrationController.scala
app/models/VatSchemeHeader.scala
app/models/api/VatScheme.scala
app/models/monitoring/SubmissionAuditModel.scala
app/models/registration/RegistrationSectionId.scala
app/repositories/VatSchemeRepository.scala
app/services/SectionValidationService.scala
app/services/submission/SubmissionService.scala
conf/registrations.routes
it/controllers/PartnersControllerISpec.scala
it/controllers/VatRegistrationControllerISpec.scala
it/controllers/registrations/RegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
it/itutil/SubmissionAuditFixture.scala
it/repository/VatSchemeRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/monitoring/SubmissionAuditModelSpec.scala
test/services/RegistrationServiceSpec.scala

SAR-10079 Added vat scheme header, updated api to support top level scheme fields

---

app/controllers/VatRegistrationController.scala
app/enum/VatRegStatus.scala
app/models/api/PersonalDetails.scala
app/services/VatRegistrationService.scala
app/services/submission/SubmissionService.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/services/RegistrationServiceSpec.scala
test/services/VatRegistrationServiceSpec.scala
test/services/monitoring/DeclarationAuditBlockBuilderSpec.scala

[SAR-10133](https://jira.tools.tax.service.gov.uk/browse/SAR-10133)
- Add new UnprocessableEntity status code for applicants that match threshold score

SAR-10133 | New UnprocessableEntity status code for applicants that match threshold score

---

app/models/BusinessEntity.scala
app/models/api/BusinessVerificationStatus.scala
test/services/submission/CustomerIdentificationBlockBuilderSpec.scala

[SAR-10192](https://jira.tools.tax.service.gov.uk/browse/SAR-10192) Add new business verification status for SA enrolment and handle registration failure case

SAR-10192 | Add new business verification status for SA enrolment and handle registration failure case

---

app/config/BackendConfig.scala
app/controllers/AttachmentsController.scala
app/controllers/VatRegistrationController.scala
app/controllers/test/RetrieveVatSubmissionController.scala
app/repositories/VatSchemeRepository.scala
app/services/AttachmentsService.scala
app/services/EligibilityService.scala
app/services/EmailService.scala
app/services/VatRegistrationService.scala
app/services/submission/SubmissionService.scala
conf/application.conf
it/controllers/AttachmentsControllerISpec.scala
it/controllers/registrations/RegistrationListSectionControllerISpec.scala
it/controllers/registrations/RegistrationSectionControllerISpec.scala
it/repository/RegistrationRepositoryISpec.scala
it/repository/VatSchemeRepositoryISpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/mocks/MockAttachmentsService.scala
test/mocks/MockEmailService.scala
test/mocks/MockVatSchemeRepository.scala
test/mocks/VatMocks.scala
test/services/AttachmentsServiceSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/EmailServiceSpec.scala
test/services/VatRegistrationServiceSpec.scala
test/services/monitoring/DeclarationAuditBlockBuilderSpec.scala
test/services/submission/AdminBlockBuilderSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-10195 Repo method cleanup

---

app/models/api/NoUKBankAccount.scala

SAR-10226 Set up new reasons bank account not provided

---

app/services/submission/BankDetailsBlockBuilder.scala
test/services/submission/BankDetailsBlockBuilderSpec.scala

[SAR-10290](https://jira.tools.tax.service.gov.uk/browse/SAR-10290)
Update bank details builder to cater for InvalidStatus

SAR-10290 | Handle bankdetails validation to cater for InvalidStatus

---

app/models/api/EligibilitySubmissionData.scala
app/models/api/vatapplication/VatApplication.scala
app/models/monitoring/SubmissionAuditModel.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/itutil/ITFixtures.scala
it/repository/VatSchemeRepositoryISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/EligibilitySubmissionDataSpec.scala
test/models/VatApplicationSpec.scala
test/services/monitoring/SubscriptionAuditBlockBuilderSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

Reverts hmrc/vat-registration#468

Revert "SAR-10342 Model and builder update for IntendingTrader change"

---

app/models/monitoring/SubmissionAuditModel.scala
app/services/submission/SubscriptionBlockBuilder.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

[SAR-10342](https://jira.tools.tax.service.gov.uk/browse/SAR-10342)
Fix registration reason to check correct status of currentlyTrading answer

SAR-10342 | Update reg-reason to check for correct currentlyTrading status

---

app/models/api/Attachments.scala

SAR-10427 Added data fields for option to tax pages

---

app/services/AttachmentsService.scala

SAR-10426 reorder attachment list so that VAT5L stays the last one

SAR-10426 reorder attachment list so that VAT5L stays the last one

---

app/models/api/AttachmentType.scala
app/services/AttachmentsService.scala
it/controllers/VatRegistrationControllerISpec.scala
it/itutil/ITVatSubmissionFixture.scala
test/mocks/MockAttachmentsService.scala
test/models/api/AttachmentTypeSpec.scala
test/services/AttachmentsServiceSpec.scala
test/services/submission/AdminBlockBuilderSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-10495 fix to attachment api to return an ordered list

---

app/models/api/Entity.scala
app/services/monitoring/EntitiesAuditBlockBuilder.scala
app/services/submission/EntitiesBlockBuilder.scala
it/controllers/VatRegistrationControllerISpec.scala
test/controllers/VatRegistrationControllerSpec.scala
test/models/api/EntitySpec.scala
test/services/submission/EntitiesBlockBuilderSpec.scala

SAR-10621 add address, telephone and email in Entity model

SAR-10621 add address, telephone and email in Entity model

---

app/config/BackendConfig.scala
app/repositories/UpscanMongoRepository.scala
app/services/SdesService.scala
conf/application.conf
test/services/SdesServiceSpec.scala

SAR-10689 Updated attachment repo TTL to 12 hours, added index and normalisation to filenames sent to sdes

---

app/models/api/UpscanDetails.scala
app/services/SdesService.scala
test/services/SdesServiceSpec.scala

SAR-10716 Updated sdes filename normaliser to also replace extension based on mimetype

---

app/services/submission/SubmissionService.scala

SAR-10727 Decoupled submission from post submission tasks that should not be blocking

---

app/services/submission/SubmissionService.scala
test/mocks/MockAttachmentsService.scala
test/services/AttachmentsServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-10732 update logging to include attachments VAT1614A and VAT1614H
**Bug fix**

SAR-10732 update logging to include attachments VAT1614A and VAT1614H

---

app/config/BackendConfig.scala
app/config/DIModule.scala
app/connectors/NonRepudiationConnector.scala
app/utils/Delayer.scala
app/utils/Retrying.scala
conf/application.conf
project/AppDependencies.scala
test/utils/DelayerSpec.scala
test/utils/RetryingSpec.scala

[SAR-10726](https://jira.tools.tax.service.gov.uk/browse/SAR-10726)
Add retry to NRS submission calls

SAR-10726 | Retry NRS calls

---

app/models/VatSchemeHeader.scala
app/models/api/VatScheme.scala
app/repositories/VatSchemeRepository.scala
app/services/AttachmentsService.scala
test/services/AttachmentsServiceSpec.scala

SAR-10767 old attachment answer cleardown, removed partner fallback code, updated vat scheme header to be more correct

---

app/models/api/SicCode.scala
test/fixtures/VatRegistrationFixture.scala
test/models/api/BusinessSpec.scala

[SAR-10771](https://jira.tools.tax.service.gov.uk/browse/SAR-10771)
Add welsh lang support for sic codes, remove indexes as not used here and in FE

SAR-10771 | Handle welsh lang for sic codes

---

app/models/api/SicCode.scala

[SAR-10771](https://jira.tools.tax.service.gov.uk/browse/SAR-10771)
Add missing default for welsh description read to avoid failures for journeys in progress

SAR-10771 | Add default read for sic code welsh description

---

app/models/api/FlatRateScheme.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/SubmissionService.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/itutil/ITFixtures.scala
it/itutil/ITVatSubmissionFixture.scala
test/fixtures/VatRegistrationFixture.scala
test/models/FlatRateSchemeSpec.scala

SAR-10767 Updated FRS model to match FE and support partial models

---

app/models/api/BankAccount.scala
app/services/submission/BankDetailsBlockBuilder.scala
it/controllers/registrations/RegistrationSectionControllerISpec.scala
it/itutil/ITFixtures.scala
it/repository/VatSchemeRepositoryISpec.scala
it/services/SubmissionAuditBlockBuilderISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/BankAccountSpec.scala
test/services/submission/BankDetailsBlockBuilderSpec.scala

Removed Overseas bank account code

---

app/controllers/registrations/RegistrationSectionController.scala
app/models/api/TransactorDetails.scala
app/services/AttachmentsService.scala
app/services/EmailService.scala
app/services/VatRegistrationService.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
app/services/submission/SubmissionService.scala
it/controllers/registrations/RegistrationSectionControllerISpec.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/models/api/TransactorDetailsSpec.scala
test/services/AttachmentsServiceSpec.scala
test/services/VatRegistrationServiceSpec.scala
test/services/monitoring/DeclarationAuditBlockBuilderSpec.scala

SAR-10947 prepped TransactorDetails model for S4L removal

---

app/models/api/ComplianceLabour.scala
app/models/api/vatapplication/AASDetails.scala
app/models/api/vatapplication/NIPCompliance.scala
app/models/api/vatapplication/OverseasCompliance.scala
app/services/monitoring/AnnualAccountingAuditBlockBuilder.scala
app/services/monitoring/ComplianceAuditBlockBuilder.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/AnnualAccountingBlockBuilder.scala
app/services/submission/ComplianceBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/itutil/ITFixtures.scala
it/repository/VatSchemeRepositoryISpec.scala
test/auth/AuthorisationSpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/DigitalContactOptionalSpec.scala
test/models/VatApplicationSpec.scala
test/services/monitoring/ComplianceBlockBuilderSpec.scala
test/services/submission/ComplianceBlockBuilderSpec.scala

[SAR-10990](https://jira.tools.tax.service.gov.uk/browse/SAR-10990)
Make Business/VatApplication and their sub model fields optional to make model ready for removal from s4l usage.

SAR-10990 | Make all fields in Business/VatApplication and their sub models optional

---

app/models/api/OtherBusinessInvolvement.scala
app/services/monitoring/SubscriptionAuditBlockBuilder.scala
app/services/submission/SubscriptionBlockBuilder.scala
it/controllers/registrations/RegistrationListSectionControllerISpec.scala
it/itutil/ITFixtures.scala
it/services/SubmissionAuditBlockBuilderISpec.scala
test/fixtures/VatRegistrationFixture.scala
test/models/OtherBusinessInvolvementSpec.scala
test/services/RegistrationServiceSpec.scala
test/services/SectionValidationServiceSpec.scala
test/services/submission/SubscriptionBlockBuilderSpec.scala

SAR-11034 updated OBI model to support S4L removal

---

app/models/api/ApplicantDetails.scala
app/services/monitoring/DeclarationAuditBlockBuilder.scala
app/services/submission/DeclarationBlockBuilder.scala
test/services/monitoring/DeclarationAuditBlockBuilderSpec.scala
test/services/submission/DeclarationBlockBuilderSpec.scala

SAR-11102 Set up the new other role field

---

app/models/api/EligibilitySubmissionData.scala
app/models/monitoring/SubmissionAuditModel.scala
app/services/EligibilityService.scala
app/services/submission/AdminBlockBuilder.scala
app/services/submission/BankDetailsBlockBuilder.scala
app/services/submission/CustomerIdentificationBlockBuilder.scala
it/controllers/EligibilityControllerISpec.scala
it/itutil/ITFixtures.scala
test/fixtures/VatRegistrationFixture.scala
test/models/EligibilitySubmissionDataSpec.scala
test/services/EligibilityServiceSpec.scala
test/services/SectionValidationServiceSpec.scala
test/services/submission/AdminBlockBuilderSpec.scala

SAR-11108 Added fixed establishment flag and updated submission to support established non uk companies

---

app/controllers/VatRegistrationController.scala
app/controllers/test/StubVatSubmissionController.scala
app/models/api/schemas/API1364.scala
app/models/api/schemas/ApiSchema.scala
app/models/monitoring/SubmissionFailureErrorsAuditModel.scala
app/repositories/VatSchemeRepository.scala
app/services/CipherService.scala
app/services/SchemaValidationService.scala
app/services/submission/SubmissionService.scala
conf/application.conf
conf/schemas/vat-registration-api-schema.yaml
test/controllers/VatRegistrationControllerSpec.scala
test/mocks/MockSchemaValidationService.scala
test/mocks/VatMocks.scala
test/models/monitoring/SubmissionFailureErrorsAuditModelSpec.scala
test/resources/test-schema.yaml
test/services/SchemaValidationServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

SAR-11133: Silence needless exceptions

---

app/services/submission/SubmissionService.scala

SAR-11133: Prevent exceptions blocking submission error audit

---

app/models/TogcCole.scala
app/models/api/Threshold.scala
app/models/api/VatScheme.scala
app/models/registration/RegistrationSectionId.scala
app/repositories/VatSchemeRepository.scala
app/services/EligibilityService.scala
app/services/SectionValidationService.scala
app/utils/EligibilityDataJsonUtils.scala
it/controllers/EligibilityControllerISpec.scala
test/models/EligibilitySubmissionDataSpec.scala
test/models/ThresholdSpec.scala
test/services/EligibilityServiceSpec.scala
test/utils/EligibilityDataJsonUtilsSpec.scala

SAR-11169 set up new field to store EL json and a runOnce method to convert the old user data

---

README.md
app/models/api/FlatRateScheme.scala

[SAR-11183](https://jira.tools.tax.service.gov.uk/browse/SAR-11183)
- Update README for the run script
- Cleanup of FRS model to remove redundant code

SAR-11183 | Readme update and FRS model cleanup

---

README.md
app/controllers/registrations/RegistrationSectionController.scala
build.sbt
conf/registrations.routes
it/connectors/NonRepudiationConnectorISpec.scala
it/controllers/registrations/RegistrationListSectionControllerISpec.scala
it/controllers/registrations/RegistrationSectionControllerISpec.scala
test/models/ThresholdSpec.scala
test/services/SectionValidationServiceSpec.scala

SAR-11201 Added some tests and added test exclusions to fix test coverage, enforced coverage minimum

---

app/controllers/UpscanController.scala
app/services/UpscanService.scala

[DL-9810] add extra logging around upscan mongo logic

---

app/services/monitoring/ContactAuditBlockBuilder.scala
app/services/submission/ContactBlockBuilder.scala
test/services/submission/ContactBlockBuilderSpec.scala

DL-10647 - changed the address to remove commas and add a space

---

app/repositories/VatSchemeRepository.scala
app/services/submission/SubmissionService.scala
app/utils/LoggingUtils.scala

[DL-11013] extra logging around failed submissions

---

app/featureswitch/api/services/FeatureSwitchService.scala
app/featureswitch/core/models/FeatureSwitchSetting.scala

Refactor feature switches

---

app/controllers/test/SetupDataController.scala
app/repositories/UpscanMongoRepository.scala
app/services/SchemaValidationService.scala
app/services/UpscanService.scala
conf/test.routes

add SetupDataController.setUpUpscan

---

conf/schemas/vat-registration-api-schema.yaml

DL-13145 update website validation

---

app/controllers/UpscanController.scala
app/models/nonrepudiation/NonRepudiationAuditing.scala
app/models/sdes/SdesAuditing.scala
app/services/SdesService.scala
app/services/UpscanService.scala
app/services/submission/SubmissionService.scala
app/utils/AlertLogging.scala
conf/application.conf
it/test/controllers/UpscanControllerISpec.scala
test/services/SdesServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

update the pagerduty alerts for upscan callback scenario

---

conf/logback.xml

DL-14425: Updated Invalid Pekko configuration

---

app/controllers/test/StubSdesController.scala

update sdescallback stub response

---

app/controllers/test/StubNrsController.scala

stub changes for nrs failed submission

---

app/controllers/test/StubNrsController.scala

update the stub for nrs submission

---

app/connectors/NonRepudiationConnector.scala
app/services/NonRepudiationService.scala

DL-14921 : add the logs for the NRS submission

---

app/services/NonRepudiationService.scala
app/services/submission/SubmissionService.scala
app/utils/AlertLogging.scala

DL-14921 : NRS submission PD alerts

---

app/controllers/test/StubNrsController.scala

test the NRS attachment failure

---

app/controllers/test/StubNrsController.scala

updated the nrs submission stub

---

app/controllers/test/StubNrsController.scala

Revert the Nrs stub changes

---

app/config/BackendConfig.scala
app/repositories/VatSchemeRepository.scala
app/services/submission/SubmissionService.scala
conf/application.conf
it/test/controllers/VatRegistrationControllerISpec.scala
it/test/itutil/ITFixtures.scala
it/test/itutil/ITVatSubmissionFixture.scala
it/test/itutil/SubmissionAuditFixture.scala

update the tt cutoff changes

---

app/services/UpscanService.scala
project/AppDependencies.scala
project/plugins.sbt
test/resources/logback.xml

DL-17169: Updated dependency for jackson-core-vulnerability
